### ISSUE TITLE
Move all explicit file paths to config.py.default ?

### ISSUE THREAD

**Issue by HastingsGreer** [mmatena/comp_755_project#13]
At my previous place of work, we often put all the hardcoded filepaths in config.py.default, with instructions in the README to copy that file to config.py and make any changes needed for the specific system that you are running the code on. Then, config.py is added to .gitignore .

 For example,

contents of config.py.default:

    dataset_dir="/pine/scr/m/m/mmatena/comp_755_project/data/"
    vae_weights_path="/pine/scr/m/m/mmatena/test_vae_train/model.hdf5"
    unet_saved_weights="/pine/scr/t/g/tgreer/unet.hdf5"
    
my local contests of config.py

    dataset_dir="/media/hastings/4083E9FE44A0B1BD/comp_755_data/"
    vae_weights_path="/media/hastings/4083E9FE44A0B1BD/comp_755_data/test_vae_train/model.hdf5"
    unet_weight_paths="/media/hastings/4083E9FE44A0B1BD/comp_755_data/unet.hdf5""

a sample script that needs a hardcoded path:

    import config
    TFRECORDS_PATTERN = (
        config.dataset_dir + "car_racing/"
        "encoded_rollouts/{split}/encoded_rollouts*"
    )

Would you support this setup? If so I can work through and make these changes.

**Comment by mmatena** [comment]
One issue that I can see with this is that we couldn't use git to get our `config.py` to the cluster. Also relying on manual updates seems like it could be a pain, especially as stuff changes.

How about something like this:

We have a `config_default.py` that contains the defaults.

Each user will then have their own config file with the name `config_$user.py`, where $user is their onyen (e.g., mmatena or tgreer).

We'll then have a `config.py` file that is like
```python
from config_default import *

import getpass
import importlib

user = getpass.getuser()

try:
    globals().update(importlib.import_module(f'config_{user}').__dict__)
except ImportError:
   print(f"No config found for f{user}. Using defaults.")
```
This way we can get our changes to the cluster using git and every user will have the same defaults that they can override if they choose. Files depending on the config can just do `import rl755.config` and have everything work.

I also think it would be a good idea to put `config.py` directly under the `rl755` folder and create a `configs` folder for the defaults and user defined configs.

**Comment by HastingsGreer** [comment]
That’s evil, I love it. Will do
